### ISSUE TITLE
超分辨率训练时，参数要和保存的扩散模型训练好的模型参数一致吗？

### ISSUE THREAD

**Issue by 4C4247** [chairc/Integrated-Design-Diffusion-Model#92]
Traceback (most recent call last):
  File "G:\foxdownload\Integrated-Design-Diffusion-Model-main\sr\train.py", line 386, in <module>
    main(args)
  File "G:\foxdownload\Integrated-Design-Diffusion-Model-main\sr\train.py", line 297, in main
    train(args=args)
  File "G:\foxdownload\Integrated-Design-Diffusion-Model-main\sr\train.py", line 143, in train
    start_epoch = load_ckpt(ckpt_path=ckpt_path, model=model, device=device, optimizer=optimizer,
  File "G:\foxdownload\Integrated-Design-Diffusion-Model-main\ut\checkpoint.py", line 57, in load_ckpt
    load_model_ckpt(model=model, model_ckpt=ckpt_model, is_train=is_train, is_pretrain=is_pretrain,
  File "G:\foxdownload\Integrated-Design-Diffusion-Model-main\ut\checkpoint.py", line 117, in load_model_ckpt
    model_weights_dict = {k: v for k, v in model_weights_dict.items() if np.shape(model_dict[k]) == np.shape(v)}
  File "G:\foxdownload\Integrated-Design-Diffusion-Model-main\ut\checkpoint.py", line 117, in <dictcomp>
    model_weights_dict = {k: v for k, v in model_weights_dict.items() if np.shape(model_dict[k]) == np.shape(v)}
KeyError: 'inc.double_conv.0.weight'

我的数据集是130*130的图片格式，貌似不是32的倍数。模型要重新训练吗？ 谢谢

**Comment by chairc** [comment]
需要时32的倍数，例如128，目前还没有提供超分模型，等后期提供超分算法的预训练模型。

**Comment by 4C4247** [comment]
意思也就是说，我如果现在用130×130跑sr/train.py的话应该是没有效果的对莫。好的，期待您的预训练模型QAQ

**Comment by chairc** [comment]
不是没有效果，可能会在卷积的时候出错，因为130/2=65，65是奇数，再进行除法操作，后期在上采样的过程中concat有可能出错。所以尽量使用2的倍数。

**Comment by 4C4247** [comment]
好的好的，明白了。谢谢你！
